### ISSUE TITLE
Image with tag 0.4.0-rc.0 not found

### ISSUE THREAD

**Issue by IvanTurgenev1** [crossplane-contrib/provider-ansible#144]
Hello! i'm trying to use last image to test inentory feature, but cannot pull it.
How i can do it?
also if i'm build provider via
Make build and push image to my own registry it's become unhealthy..

How i can use lasted provider with lasted changes?

**Comment by fahedouch** [comment]
Hi @IvanTurgenev1 ,

inventory feature is available on these docker images [main](https://hub.docker.com/layers/crossplanecontrib/provider-ansible/main/images/sha256-b2c75dfd585a73aebaaa803afe26fcf6082f3699f453c9c50a9720fb12a32999?context=explore) or [v0.4.0-rc.0.22.g8611f7b-main](https://hub.docker.com/layers/crossplanecontrib/provider-ansible/v0.4.0-rc.0.22.g8611f7b-main/images/sha256-b2c75dfd585a73aebaaa803afe26fcf6082f3699f453c9c50a9720fb12a32999?context=explore)

**Comment by IvanTurgenev1** [comment]
thanks!
