### ISSUE TITLE
CheckWhenObserve policy cycles  

### ISSUE THREAD

**Issue by fahedouch** [crossplane-contrib/provider-ansible#152]
based on [Policy CheckWhenObserve design](https://github.com/crossplane-contrib/provider-ansible/blob/main/docs/design.md#policy-checkwhenobserve); the provider makes no difference between `Create()` or `Update()` to reconcile diff if it is detected ( it will defer to the Ansible contents to determine whether it is a create or update operation)

but looking at our actual code :  
https://github.com/crossplane-contrib/provider-ansible/blob/main/internal/controller/ansibleRun/ansibleRun.go#L351-L357

the provider is determining which cycle to trigger  based on `exists` variable: 
`exists == false` => creation operation
`exists == true`  => update operation

Even if `update()` and `creation()` do the same thing, I think we should rephrase this paragraph to reflect the actual behavior or modify the code to reflect documentation.

**Comment by fahedouch** [comment]
@morningspace PTAL!

**Comment by morningspace** [comment]
Agreed. @fahedouch although, I'd say [the way](https://github.com/crossplane-contrib/provider-ansible/blob/bd292980d8c34a6e60adb10bbfd2d9b03c3f3f60/internal/ansible/ansible.go#L455-L456) that we rely on to detect whether a resource exists or not highly depends on the corresponding Ansible module's behavior, i.e.: depends on how it interprets the status `OK` and `Changed`, it is not always reliable to say resource not exists when `OK` is equal to `Changed`. But, let's see how that plays in practice. I will update the doc to reflect this.

**Comment by morningspace** [comment]
Well, just saw this PR: https://github.com/crossplane-contrib/provider-ansible/pull/170, and IIUC, this is going to update the code to reflect the original design, because I am seeing the ResourceExists always returns true, right?

**Comment by fahedouch** [comment]
@morningspace 

> it is not always reliable to say resource not exists when OK is equal to Changed

agree. this is why I introduced this [behaviour](https://github.com/crossplane-contrib/provider-ansible/pull/170/files#diff-81ab5282f8bcb328296decc2ee3d42192cd6ce44d6c6199351136b8b72d71691R363).  

But we still have to update the doc :)

the doc says : 

> It makes no difference from the provider side which lifecycle method to choose in this case, Create() or Update(), because the provider will defer to the Ansible contents to determine whether it is a create or update operation

And the code is always choosing the `update()` lifecycle method and defer to ansible-runner to determine wether it is a create or update operation. I am going to update the doc to reflect this ;)

**Comment by morningspace** [comment]
Sounds great. I've approved the PR. @fahedouch

**Comment by morningspace** [comment]
PR has been merged, so, closing it.
