### ISSUE TITLE
Image builds for ARM

### ISSUE THREAD

**Issue by AshleyDumaine** [crossplane-contrib/provider-ansible#176]
### What problem are you facing?
I'm trying to run this provider on a KIND cluster on my M1 macbook for development, but the images in Dockerhub are only for amd64 so my ansible-provider Pod gets stuck in `ImagePullBackOff`:
```
  Normal   BackOff    17s (x2 over 42s)  kubelet            Back-off pulling image "crossplanecontrib/provider-ansible:main"
  Warning  Failed     17s (x2 over 42s)  kubelet            Error: ImagePullBackOff
  Normal   Pulling    2s (x3 over 43s)   kubelet            Pulling image "crossplanecontrib/provider-ansible:main"
  Warning  Failed     1s (x3 over 42s)   kubelet            Failed to pull image "crossplanecontrib/provider-ansible:main": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/crossplanecontrib/provider-ansible:main": no match for platform in manifest: not found
  Warning  Failed     1s (x3 over 42s)   kubelet            Error: ErrImagePull
```
Can we get images built and pushed for arm64? Thanks!

**Comment by fahedouch** [comment]
Hello @AshleyDumaine , 
the actual  [main image](https://hub.docker.com/layers/crossplanecontrib/provider-ansible/main/images/sha256-02d0eec5d451e4a6550f07c959456c7ac876138f9a7f216f26d72883a7d4c925?context=explore) should support `linux/arm64` . Would you please retry and give us a feedback. Thanks

**Comment by AshleyDumaine** [comment]
Just tested it now in KIND and it works, thanks so much @fahedouch !
