### ISSUE TITLE
ProviderConfigUsage is not deleted when `AnsibleRun` is part of a composition

### ISSUE THREAD

**Issue by schinmai-akamai** [crossplane-contrib/provider-ansible#260]
### What happened?
I’m using an AnsibleRun in a composition, and instantiating a claim works perfectly. However, I’m encountering weird errors when trying to delete a claim. I see the claim’s deletion stall because the ansiblerun never gets deleted. I’m seeing a ProviderConfigUsage linger, with its owner set to the ansiblerun. I’m using the default ObserveAndDelete runpolicy, and I’ve set spec.deletionPolicy to Orphan

### How can we reproduce it?

I can email a gist to reproduce 

### What environment did it happen in?
Crossplane version: 

Crossplane: 1.13.2
Kubernetes Version: v1.26.7+rke2r1
Kubernetes distribution: rke2
OS: Ubuntu 22.04
Kernel: `5.15.0-83-generic #92-Ubuntu SMP Mon Aug 14 09:30:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by janwillies** [comment]
I don't use a composition and still `ProviderConfigUsage` is not cleaned up. `spec.deletionPolicy` is set to `Delete`
