### ISSUE TITLE
Support specifying inventory when create AnsibleRun

### ISSUE THREAD

**Issue by morningspace** [crossplane-contrib/provider-ansible#64]
### What problem are you facing?

The current [design doc](https://github.com/multicloudlab/crossplane-provider-ansible/blob/main/docs/design.md) does not allow users to specify inventory information. This prevents provider ansible from running Ansible contents on remote hosts. Right now, it can only run Ansible contents locally within the same host where the provider ansible runs, e.g.: to manage in-cluster k8s resources, manage public cloud resources, but cannot run Ansible contents remotely on a set of machines.

### How could Crossplane help solve your problem?

Both the design and implementation would need to be updated to add the support of inventory, so that user can specify inventory information when creating AnsibleRun custom resource. It can be inlined or reference to secret or configmap which includes all hosts information required for Ansible contents run with. The hosts information will ultimately be stored into the working directory along with the Ansible contents, and be picked up by passing through as an input argument when ansible-runner is called.

**Comment by fahedouch** [comment]
@morningspace I was thinking about this feature. Based on our design, the inline mode is intended  for simple use cases (e.g tests..) so not supporting inventory in the `inline mode` make sens as it allows testing some simple playbooks without dealing with complex ansible configuration. Now regarding the `remote mode`, I think it is easier to deal with inventory as ansible content, so we assume that the inventory is already present in the remote repository. 
==> if we are ok with this design, we have to update the design doc on this way: highlight the use of inventory only with remote mode

**Comment by morningspace** [comment]
@fahedouch It could be possible to store inventory along w/ the ansible contents in a remote repository, but given that inventory information are sensitive to the target systems that you run w/, usually it may not be included in public ansible roles such as those shared via Ansible Galaxy. Another reason is that, it may include credentials to access target systems, which usually cannot be simply stored in a repo due to security concerns. With that, it may be better to set inventory as runtime information, which I think k8s secret is the best place to host such data.

**Comment by fahedouch** [comment]
fixed by https://github.com/crossplane-contrib/provider-ansible/pull/132
